theme: jekyll-theme-midnight
title: Aryaman Singh Samyal
description: Figuring out the coherence of a pot of chaos, that is life. Quoting Socrates, "To know is to know, you know nothing". This, I find incredibly intriguing as it essentially means, you can never achieve the singularity of life. However, is not this what the answer to life exactly is?
